services:
  - docker

sudo: required

before_script:
  - cp .env.travis .env
  - source bin/build_travis

script:
  - ./bin/travis_checks

after_success:
    - bash <(curl -s https://codecov.io/bash)
