version: "3"
services:
  web:
    image: jameslyon42/web
    container_name: blog_web
    ports: 
      - "80:80"
    volumes:
      - ./:/var/www/site
  db:
    image: percona
    container_name: blog_db
    ports:
      - "5123:5123"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
